- name: nginx installing 
  hosts: nginx
  # hosts: all 
  become: yes  #taking the sudo access 
  serial: 3
  tasks: 
  - name: install nginx 
    ansible.builtin.package:
      name: nginx
      state: present 

  - name: to run nginx 
    ansible.builtin.service: 
      name: nginx 
      state: started 
      enabled: yes 