- name: install nginx serverr
  ansible.builtin.package:
    name: nginx
    state: present

- name: start nginx server
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: import tasks from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre

# - name: remove html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: create html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory
  
# - name: download frontend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: extract the code
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: copy expense conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx 

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted 